### ISSUE TITLE
doc: GivenWhenThen -> steps, fixtured are shared

### ISSUE THREAD

**Issue by cassus** [Niitch/gherkin-wrapper#1]
First of all Wow @Niitch thank you, this looks very promising, maybe you're solving my biggest issue with cucumber-js!

I haven't tried it hands on, but checked out the readme and the examples, also some of the code, and I have a few questions (maybe they are also worth clarifying in the readme).

How does the Gherkin steps convert to playwright tests/steps?
Is one Scenario/Example turned into one pw test?
Are the test level fixtures shared between the GivenWhenThen steps?
Are the GivenWhenThen steps translated to playwright `test.step`s for reporting?
Sharing test-level fixtures would be super important to share state between the GivenWhenThen step implementations.

**Comment by Niitch** [comment]
Hi @cassus, thank you for your feedback. 

> How does the Gherkin steps convert to playwright tests/steps?
> Is one Scenario/Example turned into one pw test?

Each step converts to a playwright `test.step` and a `Scenario/Example` converts to a `test`.

The wrapper also handles these Gherkin keywords:
- `Background` converts to `test.beforeEach`
- `Feature` and `Rule` convert to `test.decribe`
- `Scenario outline` converts to a `test` for each example in it

If needed, all of this could become fully customizable in the future.

> Are the GivenWhenThen steps translated to playwright test.steps for reporting?

The wrapper calls directly the playwright `test` API, so each part converted from the feature file (as presented above) should appear as it used to in the reporting.
The titles for steps, tests and test groups are the text of the corresponding objects in the feature file.

The usual reporters should work fine but i recommend exending them or implementing yours for better support.

> Are the test level fixtures shared between the GivenWhenThen steps?
> Sharing test-level fixtures would be super important to share state between the GivenWhenThen step implementations.

As each Scenario/Example translates to a test, the steps in a Scenario/Example share there fixture instances at runtime.

Step functions defined with the given-when-then wrapper methods are not tied to a particular fixture instance.
In fact, needed fixtures for a test are loaded based on its steps indivual requirements when it is created.
This way step functions can be reused mutiple times for different tests during the same execution.

A hidden feature is to reuse or prebuild step function libraries. In the example below, wrappers A and B share the same step function library (both handles spec 1, 2 and 3) but will be able to pass different fixtures to them.

```typescript
import { Library } from 'gherkin-wrapper/common/library'

const library = new Library()

library.given('spec 1', ({}) => {...})

const wrapperA = new GherkinWrapper.forPlaywright(test.extends({...fixturesA}), library) 

wrapperA.when('spec 2', ({}) => {...})
wrapperA.then('spec 3', ({}) => {...})

const wrapperB =  new GherkinWrapper.forPlaywright(test.extends({...fixturesB}), wrapperA.library) 
```

---

__After collecting more feedback, I'll build an extended version of the documentation section you found in the README.__

**Comment by cassus** [comment]
Works great, thanks!

Maybe also add a world fixture as an example to the documentation:

```ts
type Fixtures = {
  world: Record<string, unknown> & {
    userId?: string // or any other typed params
  }
}

const test = baseTest.extend<Fixtures>({
  world: async ({}, use) => {
    // Mutable
    const currentWorld = {}
    await use(currentWorld)
  },
})
```
