### ISSUE TITLE
[Question] - More detailed examples and documentation

### ISSUE THREAD

**Issue by NikkTod** [Niitch/gherkin-wrapper#10]
@cassus @Niitch - Sorry guys, but I am very new to JS/TS, I was hoping you could help me and maybe update a bit more the 'how to/read me' doc with full working feature examples.

What would be the step definitions when we want to pass a single string?

`Given I open url "https://playwright.dev"`

I am trying with something similar to below lines of code, but I dont know how to pass the parameter from the feature file. 

```
wrapper.given(/I open url "(.*)"/, async ({ page }) => {
    await page.goto(?????);
})
```

What would be the step definitions when we have data table?

```
When I fill the following form
| name                | address       | phone          |
| some string      | some string | some string |
```

**Comment by Niitch** [comment]
The step function you reegister with the wrapper `given`/`when`/`then` methods can take a second parameter that is an object defined like so:
```typescript
interface WrapperArg {
    match?: RegExpMatchArray, // result of the match between the step function spec and the step text from the feature file
    dataTable?: DataTable, // a cucumber DataTable representing the one you might have attached to the step
    docString?: string, // the content of the docstring you might have attached to the step
}
```
See [@cucumber/cucumber](https://github.com/cucumber/cucumber-js/blob/63f30338e6b8dbe0b03ddd2776079a8ef44d47e2/src/models/data_table.ts#L3) for the `DataTable` class definition

For your examples, you could have register these step functions:
```typescript
wrapper.given(/I open url "(.*)"/, async ({ page }, { match }) => {
    await page.goto(match[1])
})
wrapper.when(/I fill the following form/, async ({ page }, { dataTable }) => {
    for (const line of dataTable.hashes()) {
        await page.getByLabel(...).fill(line.name)
        await page.getByLabel(...).fill(line.address)
        await page.getByLabel(...).fill(line.phone)
    }
})
```

**Comment by cassus** [comment]
Hi @NikkTod !

Let's see

> What would be the step definitions when we want to pass a single string?
> 
> `Given I open url "https://playwright.dev"`

```ts
wrapper.given(/I open url "(.*)"/, async ({ page }, { match }) => {
  const url = match![1]!
  await page.goto(url)
})
```

The `!` is the (bit obscure) [Non-null Assertion Operator](https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#non-null-assertion-operator-postfix-). You might instead want to check the values runtime based on how much explicit error checking you like in your test files. Eg:

```ts
bdd.given(/I open url "(.*)"/, async ({ page }, { match }) => {
  if (!match) throw new Error("No match found")
  const url = match[1]
  if (!url) throw new Error("No url found")
  await page.goto(url)
})
```

( @Niitch I'm thinking about how to best integrate zod to these scenarios, that might help with understandability of the code, type safety, and with debugging when something goes wrong.  I'll create an issue when I have something. Not sure if it should be part of this lib, just sharing with you and the community. )

**Comment by cassus** [comment]
And here's an example from our product code for the dataTable part of your questions @NikkTod 


```feature
            And Choice responses
                | Q1 | Q2 |
                | A  | B  |
                | B  | A  |
```

```ts
bdd.given("Choice responses", async ({ world }, { dataTable: dataPickle }) => {
  // TODO https://github.com/Niitch/gherkin-wrapper/issues/5
  const tableRows = new DataTable(dataPickle as PickleTable).rows()

  const responsesToAdd = tableRows.map((answers) =>
    makeChoiceResponse(world.survey!.survey, answers),
  )

  await addResponses(responsesToAdd)
})
```

**Comment by NikkTod** [comment]
@Niitch , @cassus, great stuff guys, exactlly the examples I am looking for, will try them out. 

Thank you 💯
