### ISSUE TITLE
can't import PlaywrightLibrary in the documented way

### ISSUE THREAD

**Issue by cassus** [Niitch/gherkin-wrapper#15]
Hi, I'm back from a long holiday and trying to upgrade to the latest 0.4.0 version. 

I saw the following doc https://github.com/Niitch/gherkin-wrapper/blob/dfb885e9ec3814687692e59989fde85c361c637c/src/playwright/index.ts#L24

but when I try to do this this I get `Module '"gherkin-wrapper"' has no exported member 'PlaywrightLibrary'.`

And when I open `node_modules/gherkin-wrapper/lib/index.d.ts` I also don't see any mention of `Library` or `PlaywrightLibrary`

```
import { PlaywrightWrapper } from './playwright';
import { JestWrapper } from './jest';
declare const _default: {
    forPlaywright: typeof PlaywrightWrapper;
    forJest: typeof JestWrapper;
};
export default _default;
```

As a workaround I found that I can import it from `import { PlaywrightLibrary } from "gherkin-wrapper/lib/playwright"`

**Comment by Niitch** [comment]
It seems I forgot some exports. You can upgrade to 0.4.1 to get it fixed.

The workaround you found is intended. Also I recommend using `compilerOptions.moduleResolution = "NodeNext"` in your tsconfig to shorten the import path ot `"gherkin-wrapper/playwright"`.

Let me know if this works for you

**Comment by cassus** [comment]
Thanks it works!

```ts
import { PlaywrightLibrary } from "gherkin-wrapper"
``` 

imports as expected
