### ISSUE TITLE
"TypeError: body is not a function" when using playwright/test 1.39.0

### ISSUE THREAD

**Issue by akong-anaconda** [Niitch/gherkin-wrapper#17]
I tried running the tests in `tests/simple.feature` with `playwright/test` 1.39.0 and got this TypeError:
``` 
 1) [chromium] › ../simple.feature:4:3 › Guess the word › Maker starts a game › [object Object] ───

    TypeError: body is not a function

       at ../../src/playwright/wrapper.ts:172

      170 |     type RuntimeRunnerArgs = Parameters<StepFunction<RunnerArgs<T>>>[0] & Parameters<StepHook<RunnerArgs<T>>>[1];
      171 |
    > 172 |     await this._step(args.step.location, args.step.keyword + args.step.text, async () => {
          |                ^
      173 |       await Promise.all(
      174 |         this.hooks.triggerLifecycle(
      175 |           'beforeStep',

        at PlaywrightWrapper.runStep (/Users/akong/gherkin-wrapper/src/playwright/wrapper.ts:172:16)
        at /Users/akong/gherkin-wrapper/src/playwright/wrapper.ts:163:43
        at eval (/Users/akong/gherkin-wrapper/<anonymous>:3:17)
```

No errors when running with version 1.38.1 or earlier. I didn't spot anything in the release notes for 1.39.0 that would break things:
https://github.com/microsoft/playwright/releases/tag/v1.39.0

Will look more into this myself to see if I can figure out what's happening but would love another set of eyes since I'm not sure where to start investigating this issue. Thanks!

**Comment by Niitch** [comment]
Issue fixed in version 0.5.0

They changed the way playwright test steps are generated

Thanks for sharing and sorry for the delay
