### ISSUE TITLE
provide the @cucumber/cucumber (more useful) dataTable

### ISSUE THREAD

**Issue by cassus** [Niitch/gherkin-wrapper#5]
the `import { DataTable } from '@cucumber/messages'` is very basic, I tend to always do the following:

```ts
import { DataTable } from "@cucumber/cucumber"
// ...
  wrapper.then("xx",({},{ dataTable: dataPickle }) => {
    const dataTable = new DataTable(dataPickle as PickleTable)
```

I think this would be a better value for dataTable, and maybe pass a rawDataTable if someone needs that.

**Comment by cassus** [comment]
I'm happy to try creating a PR for this. @Niitch would you like that?

**Comment by Niitch** [comment]
Thank you for your feedback.

I applied your suggestion on the [dev branch](https://github.com/Niitch/gherkin-wrapper/tree/dev)

This change makes npm download the whole cucumber package as a dependency. It could be better to somehow extract the DataTable class from the cucumber package.

**Comment by cassus** [comment]
Wow, You are quick :D
