### ISSUE TITLE
option to fail the test when a step is missing

### ISSUE THREAD

**Issue by cassus** [Niitch/gherkin-wrapper#6]
I'd like an option to get an get a failure when a step is missing, instead of skipping the test

Maybe there could be a way to explicitly mark Scenarios as non-automated, `@skip` maybe? as minimum version commenting them out works fine.

**Comment by Niitch** [comment]
Thank you for your feedback.

I started building a hook system based on both the wrapper test automation lifecycle and the tags that could be found in the feature file. (see #8)

You could fail your tests like so:
```typescript
wrapper.beforeAutomation(({ fn }) => {
    test.fixme(!fn, 'Not automated')
})

// or

wrapper.on('@skip', () => {
    test.skip()
})
```

Let me know if this is what you were looking for

**Comment by cassus** [comment]
Yes! This would be amazing!
