### ISSUE TITLE
Support asterisk-only Example bodies

### ISSUE THREAD

**Issue by cassus** [Niitch/gherkin-wrapper#9]
I'm thinking about adding some storybook variants to my living bdd documentation

```feature
[...]
Rule: Displays multiple questions on the same step
    Example:
        * Storybook: MultiQuestionStep / ChoiceAndLongText
        * Storybook: MultiQuestionStep / StatementAndChoice
```

These "steps" serve as documentation and links to the visual tests, 
when executed they can check if the mentioned storybook pages exists.
(I use chromatic for visual regression testing, but in theory this is an implementation detail and the visual regression test could also be ran inside these steps)

### Current behavior 
```
Error: First step cannot be of type Conjunction or Unknown.
    at usableStepType (.../node_modules/gherkin-wrapper/lib/common/library.js:11:15)
```

### Expected behavior

Find the matching `given` / `when` / `then` step definition and execute it

What do you think @Niitch ?

**Comment by Niitch** [comment]
I'll make use of the _unknown_ keyword (*) allowed everywhere. The current behaviour for _conjunction_ keywords (and, but, ...) won't change.

I thought of 2 behaviours that could work together:
1. Add a `any` method that works like `given`/`when`/`then` but for the `*` keyword.  This one will solve your issue
2. If a given/when/then step do not find a match for its keyword type, then the wrapper search through the _any_ step functions

**Comment by cassus** [comment]
Sounds great, thanks @Niitch !
